### ISSUE TITLE
Google Code-In logo

### ISSUE THREAD

**Issue by vijay35** [JBossOutreach/gci.jbossoutreach.org#115]
![screenshot - 1_16_2018 6_43_43 pm](https://user-images.githubusercontent.com/30561536/34990737-3570237e-faed-11e7-9730-760a3c65489b.png)
See this picture. When I visit [JBoss communities home page](https://gci.jboss-outreach.org/) the Google Code-In logo is down.
Operating system: Windows 10
browser: google chrome

**Comment by divyanshkul** [comment]
Hey! thanks for reminding @vijay35 I was working on this, will make a PR very soon :)

**Comment by vijay35** [comment]
waiting for it @divyanshkul
