### ISSUE TITLE
Update Travis Badge and its redirection link

### ISSUE THREAD

**Issue by aashutoshrathi** [JBossOutreach/gci.jbossoutreach.org#123]
Change the links as we have shifted from `jboss-outreach` to `JBossOutreach`

**Comment by Ananthavijay** [comment]
Will do it @aashutoshrathi  Could u assign me this?

**Comment by aashutoshrathi** [comment]
Go for it.

**Comment by Ananthavijay** [comment]
How to solve this issue? @aashutoshrathi

**Comment by aashutoshrathi** [comment]
Change the link and redirection of Travis Badge to new one

**Comment by Ananthavijay** [comment]
which file to change and where is the Travis badge? @aashutoshrathi . I am just starting about travus

**Comment by aashutoshrathi** [comment]
No, the badge link in README :sad:

**Comment by Ananthavijay** [comment]
Sorry @aashutoshrathi  I first went into the read me to check whether there was Travis badge. I thought Travis badge would be named Travis. So I asked the question here. @aashutoshrathi we have many files to change the links I think

**Comment by Ananthavijay** [comment]
This PR fixes the [issue](https://github.com/JBossOutreach/gci/pull/124)

**Comment by Ananthavijay** [comment]
All the best for your exam

**Comment by Ananthavijay** [comment]
This could be closed @aashutoshrathi

**Comment by aashutoshrathi** [comment]
Sure @Ananthavijay 😄
