### ISSUE TITLE
Some link have not been updated in index.html

### ISSUE THREAD

**Issue by Ananthavijay** [JBossOutreach/gci.jbossoutreach.org#129]
Change the jboss-outreach to JbossOutreach and remove the links which are not working..

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by aashutoshrathi** [comment]
This is an immediate change we need

**Comment by prithaupadhyay** [comment]
Claiming.

**Comment by Ananthavijay** [comment]
after merging https://github.com/JBossOutreach/gci.jbossoutreach.org/pull/132
This could be closed @aashutoshrathi @prithaupadhyay
