### ISSUE TITLE
Logo getting misplaced from navbar

### ISSUE THREAD

**Issue by DivyeshPuri** [JBossOutreach/gci.jbossoutreach.org#144]
**Expected Behaviour**

The logo should stay inside the navbar when the screen size is reduced.

**Steps to reproduce it**

Entering into the responsive mode will trigger this issue.

**Screenshots of the issue**

![logo](https://user-images.githubusercontent.com/23422478/46021268-e8cfee00-c0fd-11e8-944f-5fd37a4ba994.PNG)

**Would you like to work on the issue?**

No

**Comment by samagragupta** [comment]
Can I work on it ?

**Comment by Ananthavijay** [comment]
Yeah @samagragupta go ahead

**Comment by Ananthavijay** [comment]
@DivyeshPuri Actually the logo in navbar doesnt get displayed. Check it by making the browser zoom to 90% u could see rest of the logos

**Comment by DivyeshPuri** [comment]
@Ananthavijay What I am pointing is when you will see the site in responsive mode or via toggle device mode in chrome, you will see the "JBoss Community" logo getting misplaced from the navbar.
