### ISSUE TITLE
Navigation Bar collapsing issues

### ISSUE THREAD

**Issue by divyanshkul** [JBossOutreach/gci.jbossoutreach.org#166]
**Expected Behaviour**
- On clicking outside the navigation bar, the navigation bar should close
- On clicking one of the navigation menu-items, the navbar should collapse smoothly. (Right now we are forcefully collapsing it)

**Steps to reproduce it**
1. Using bootstrap's inbuilt collapse component
2. Detecting if there is an outside click

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes

**Comment by Nienormalny** [comment]
I can do this for you :)

**Comment by divyanshkul** [comment]
@Nienormalny sorry, I already fixed it. Btw feel free to look at other repos/issues of our organisation :)
