### ISSUE TITLE
Project names are not being displayed

### ISSUE THREAD

**Issue by PrajwalM2212** [JBossOutreach/gci.jbossoutreach.org#170]
**Expected Behaviour**
The project name should be displayed

**Screenshots of the issue**

<img width="1680" alt="screen shot 2018-10-02 at 3 11 20 pm" src="https://user-images.githubusercontent.com/30733262/46341392-93439600-c655-11e8-9e7f-d8c53497311d.png">

**Would you like to work on the issue?**
Yes

**Comment by aashutoshrathi** [comment]
Sure, take it

**Comment by PrajwalM2212** [comment]
@aashutoshrathi 
<img width="1680" alt="screen shot 2018-10-02 at 3 33 16 pm" src="https://user-images.githubusercontent.com/30733262/46342506-88d6cb80-c658-11e8-9d12-0212e85b2136.png">

There was nothing wrong with the code . The rate limit for `https://api.github.com/orgs/JBossOutreach/repos` had exceeded . Now it is functioning.

**Comment by aashutoshrathi** [comment]
Use #134 instead
