### ISSUE TITLE
Top image slider for GCI website

### ISSUE THREAD

**Issue by KeenWarrior** [JBossOutreach/gci.jbossoutreach.org#20]

**Comment by aashutoshrathi** [comment]
This is done and should be closed, right? @garg-anuj

**Comment by learneradarsh** [comment]
https://github.com/jboss-outreach/gci/issues/99

**Comment by Ananthavijay** [comment]
This could also be closed @KeenWarrior

**Comment by aashutoshrathi** [comment]
Sure @Ananthavijay 
cc: @KeenWarrior
