### ISSUE TITLE
Issues with gci tag on entire org needed to be displayed on gci website.

### ISSUE THREAD

**Issue by KeenWarrior** [JBossOutreach/gci.jbossoutreach.org#21]
* Create/Update issues section on gci website.
* Create ajax call to fetch issue data from github
* Sort by date created and display latest 10 in issues section

**Comment by C0d3rThomas** [comment]
The task is *"Issues with `codein` tag on GitHub org of JBoss Outreach needed to be displayed on gci website"*, but directs you to this issue where it is explicitly asked for tasks with the `gci` tag to be shown on the issues section.

**Comment by Ananthavijay** [comment]
@KeenWarrior I think this could be closed
