### ISSUE TITLE
Improving codacy grade of the project

### ISSUE THREAD

**Issue by sidhyatikku** [JBossOutreach/gci.jbossoutreach.org#47]
<img width="1680" alt="screen shot 2017-12-16 at 12 39 22 pm" src="https://user-images.githubusercontent.com/33092447/34068308-9026d742-e25e-11e7-8311-317e15ca4309.png">

will start fixing these

**Comment by SachinRammoorthy** [comment]
@sidhyatikku perhaps you could close this issue now that the PR has been merged...

**Comment by starkblaze01** [comment]
@sidhyatikku , please close this issue if it is resolved.

**Comment by aashutoshrathi** [comment]
@starkblaze01 There are still chances for improvement.
We still have Codacy Code Quality Grade B. 😅
