### ISSUE TITLE
Navigation bar issues 

### ISSUE THREAD

**Issue by divyanshkul** [JBossOutreach/gci.jbossoutreach.org#73]
- [ ] The nav bar covers up some part of the heading (when the clicked heading is reached)
- [ ] The nav bar has a missing link which is present in the main website.
- [ ] The nav looks really big, will make its styling little better
- [ ] There is a little space left just above the slideshow container on the landing of the page.

I am working on these issues and will make a pull request within sometime in an attempt to fix these. :)

**Comment by SachinRammoorthy** [comment]
Hey @divyanshkul . Two of these issues have already been addressed in PR #72 . (Little space above slideshow container and cover-up of headings).

**Comment by divyanshkul** [comment]
@SachinRammoorthy let me make my PR first, then you can comment further. :)

**Comment by divyanshkul** [comment]
@SachinRammoorthy as the 3rd and 4th points here are interlinked.

**Comment by SachinRammoorthy** [comment]
Now that the PR has been merged, perhaps this issue can be closed?

**Comment by SachinRammoorthy** [comment]
Now that the PR has been merged, perhaps this issue can be closed?

**Comment by starkblaze01** [comment]
@divyanshkul , Please close this issue if already resolved.
