### ISSUE TITLE
User hits the GitHub API rate limit too easily

### ISSUE THREAD

**Issue by zwliew** [JBossOutreach/gci.jbossoutreach.org#96]
Currently, the first access to the website takes up 30-40 GitHub API requests, which is around half of the rate limit for unauthenticated requests (see: https://api.github.com/rate_limit).

This means that it's really easy and quick for users to hit the rate limit.

**Would you like to work on the issue?**
Yes. #95.

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by aashutoshrathi** [comment]
Shifted to #134
