### ISSUE TITLE
Image Slider is not working fine in mobile view

### ISSUE THREAD

**Issue by learneradarsh** [JBossOutreach/gci.jbossoutreach.org#99]
**Bug Description**
Both 'Check us out!' and 'Read' button on a slider in mobile view overlaps the top navigation bar.
**My OperatingSystem**
Ubuntu 16.04  LTS
**Browser**
Google Chrome Version 60.0.3112.113
**Issue Log**
![screenshot from 2018-01-03 20-27-43](https://user-images.githubusercontent.com/18267421/34526010-fd24ea70-f0c6-11e7-8044-26d2454a5c11.png)
![screenshot from 2018-01-03 20-27-26](https://user-images.githubusercontent.com/18267421/34526093-55c82f8e-f0c7-11e7-85ba-25ab8e815acd.png)
**Suggestions to Solve this Issue**
We can solve this issue by using top margin for buttons in CSS styling codes.
Example:
<button style="margin-top:15px;">Read</button>
Please don't use as it as in real code it's only for example.
**Would you like to work on the issue?**
No

**Comment by starkblaze01** [comment]
@learneradarsh , this problem has been resolved, you can close this issue now.
